services:

  monitoring:
    build: ./monitor_reservation
    container_name: monitor_reservation
    ports:
      - "5001:5000"
    depends_on:
      - reservation

  reservation:
    build: ./Reservation
    container_name: reservation
    ports:
      - "8080:5000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"