global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alert.reservation.rules.yml"
  - "alert.inventory.rules.yml"

scrape_configs:
  - job_name: "reservation-monitoring"
    static_configs:
      - targets:
          - monitor_reservation:5000
  - job_name: "inventory-monitoring"
    static_configs:
      - targets:
          - monitor:5005