global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: cart_service_metrics
    static_configs:
      - targets: ["cart_service:5001"]
    metrics_path: /metrics

  - job_name: order_service_metrics
    static_configs:
      - targets: ["order_service:5002"]
    metrics_path: /metrics

  - job_name: http_echo_probe
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://cart_service:5001/echo
          - http://order_service:5002/echo
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
